# Generated by Django 4.0 on 2021-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(max_length=40),
        ),
    ]
